### ISSUE TITLE
Run.Log'a Versiyon Bilgisi Eklenmesi

### ISSUE THREAD

**Issue by cancu** [enginberkay/Deve#3]
Run.log dosyasının başına, Deve'nin versiyon bilgisinin eklenmesi ile hangi versiyon ile geçiş yapılmış anlayabileceğiz.

**Comment by enginberkay** [comment]
Şuan ki master branch'in de bu özellik hardcoded mevcut. 
İyleştirme yapmaya çalışacağım fakat versiyon bilgisini nasıl tutmam gerektiği konusunda kafam karışık.
